# Generated by Django 4.2.7 on 2024-01-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('live_url', models.URLField()),
                ('gighub_url', models.URLField()),
                ('tech', models.CharField(max_length=200)),
            ],
        ),
    ]
