# Generated by Django 4.2.7 on 2024-01-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='gighub_url',
            new_name='github_url',
        ),
    ]
